# Generated by Django 5.2.14 on 2026-06-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='uploads/')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('VERIFYING', 'Verifying'), ('NORMALIZING', 'Normalizing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
