# Generated by Django 5.2.14 on 2026-06-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='records_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
